### PR TITLE
Send all progress logging messages to stderr.

### PR DESCRIPTION
**Pull request by dmaahs2017**
Adresses #169. 

- Send logging messages to stderr instead of stdout so pagers do not intercept them.
- Updated tests to match these changes.
- Changed test_markdown_rendering to no longer rely on the tldr pages
       repo. Instead manually adding a known page to use in this test,
       because it failed due to the tldr pages repo updating this command (so
       it no longer matched our expected output, which shouldn't cause our
       tests to fail).

### CODE REVIEW

**Comment by niklasmohrin** [comment]
To keep this consistent with the rest of the program, messages like "Successfully deleted cache." should also be printed on stderr. Maybe even the "page not found" output, but I am not sure about that one. (@dbrgn ?)

@dmaahs2017 As you can see, the tests have to be updated accordingly, but that should be a quick fix

**Review by dbrgn — CHANGES_REQUESTED** [review]
This is a good thing to do (no matter how we handle the paging issue). However, the tests need an update (expect the string in stderr, not stdout).

@dmaahs2017 can you update the tests as well?

**Comment by dmaahs2017** [comment]
Ready for re-review. @niklasmohrin @dbrgn

**Review by dbrgn — APPROVED** [review]
Thanks, LGTM!

**Pull request merged**
