### PR TITLE
Add cache dir config in configuration file.

### PR DESCRIPTION
**Pull request by hgaiser**
This PR started as just adding a `cache_dir` option to the configuration file, but in the process I had to refactor some functions.

Mainly I moved some functionality for the cache inside the cache struct and let it own a `PathBuf` to the cache dir.

This fixes https://github.com/dbrgn/tealdeer/issues/156 .

### CODE REVIEW

**Comment by niklasmohrin** [comment]
@hgaiser Do you want to keep working on this, or can we reassign this if someone else comes along? (Both options are equally valid)

**Comment by hgaiser** [comment]
Ah sorry, I don't think I'll have time to work on this anytime soon. Feel free to reassign to someone else 👍

**Comment by hgaiser** [comment]
Yep makes sense! Sorry for not following up on this.

**Comment by niklasmohrin** [comment]
Note that I also have some thoughts in #266

**Comment by dbrgn** [comment]
Replaced by #276.

**Comment by dbrgn** [comment]
> Note that I also have some thoughts in https://github.com/dbrgn/tealdeer/pull/266

Aaaah, I never saw that! Sorry very much about that 😞 I'll take a look at it, to see if we independently got to the same conclusions, or whether we can merge our approaches.

**Pull request closed without merging**
