### PR TITLE
Add cargo fmt to github-actions config

### PR DESCRIPTION
**Pull request by Atul9**

### CODE REVIEW

**Comment by dbrgn** [comment]
@Atul9 thanks! I rebased the branch for you and did a few adjustments to the CI config.

**Comment by Atul9** [comment]
Thank you @dbrgn I have pushed a commit to fix this build failure - https://github.com/dbrgn/tealdeer/pull/119/checks?check_run_id=1048103561 & its fixed in this build - https://github.com/dbrgn/tealdeer/pull/119/checks?check_run_id=1048163935

**Comment by dbrgn** [comment]
Thanks @Atul9. The build fails because rustfmt 1.39 and 1.46 use slightly different rules. (That's why I prefer a fixed version in CI :slightly_smiling_face:)

I will bump the rustfmt rust version, but first I'll raise the version used for clippy in a separate PR.

If it's OK, I'll rebase your branch again once that's merged. If you prefer to do the rebasing / adjustments yourself, just let me know :slightly_smiling_face:

**Comment by Atul9** [comment]
it's ok, you can rebase my branch.

**Comment by dbrgn** [comment]
Finally, thanks :slightly_smiling_face:

**Pull request merged**
