### PR TITLE
add -q, --quiet flag to surpress non-error output

### PR DESCRIPTION
**Pull request by jedahan**
First pass at #46, tests pass and manual testing looked good.

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks, that was fast :) PR looks good.

The README is missing an update with the new command. Furthermore, I currently prefer if the version bump is only done on release. But I can fix these two issues myself.

**Comment by dbrgn** [comment]
One more thing: Could you add a few small tests for this? You can take a look at `tests/lib.rs` for reference, for example `test_missing_cache`. Thanks to [assert_cli](https://docs.rs/assert_cli/0.5.6/assert_cli/) it's very simple to call the binary and to verify the output.

**Comment by jedahan** [comment]
K, added tests. A bit hacky but seem to work.

**Comment by dbrgn** [comment]
Nice, thanks @jedahan!

**Comment by dbrgn** [comment]
Merged in 8784b55.

**Pull request closed without merging**
