### PR TITLE
Upload to crates.io

### PR DESCRIPTION
**Pull request by dbrgn**
I'd like to put a version of tldr on crates.io that supports an offline cache. The name is already taken though (rilut/rust-tldr#1).

Therefore I'd go with another name. A few ideas:

- toolong
- tldr-rs

Any other ideas? The binary name could also be different from the crate name I guess.

cc @SShrike

### CODE REVIEW

**Comment by dbrgn** [comment]
There we go. I did the rename manually with [ack](http://beyondgrep.com/).

I guess we should rename the repository as well... Can you think of any unintended consequences besides CI tools like Travis & co?

**Comment by SShrike** [comment]
I don't think there should be any other problems, as GitHub should redirect any existing links to this repository.

**Comment by dbrgn** [comment]
Awesome, Travis automatically renames the project!

**Comment by SShrike** [comment]
Yeah it's a nice feature.

**Comment by SShrike** [comment]
Don't forget to send a PR to [tldr-pages/tldr](https://github.com/tldr-pages/tldr) about changing the repository link.

**Comment by dbrgn** [comment]
What about this? :wink: 

https://github.com/dbrgn/tealdeer/blob/namechange/README.md

**Comment by SShrike** [comment]
That's great hahaha :+1: 

Don't forget to also rename the [Coveralls repo](https://coveralls.io/github/dbrgn/tldr-rs).

**Comment by dbrgn** [comment]
This one would also have been funny: https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/RedDeerSkelLyd2.png/533px-RedDeerSkelLyd2.png

Yeah, thanks for the note.

**Comment by SShrike** [comment]
Ah, but that one wouldn't of worked since it's the skeleton of a red deer :wink:

**Comment by dbrgn** [comment]
The upload will happen in a moment.

**Comment by SShrike** [comment]
:tada:

**Comment by dbrgn** [comment]
Everything should be done now. PR is pending: tldr-pages/tldr#850

**Pull request merged**
