### PR TITLE
Update benchmarks

### PR DESCRIPTION
**Pull request by niklasmohrin**

### CODE REVIEW

**Comment by niklasmohrin** [comment]
Ah, actually bash tldr changed URLs. Will add back later

**Comment by dbrgn** [comment]
> Ah, actually bash tldr changed URLs. Will add back later

Do you want this PR already merged, or do you want to re-add tldr-bash first?

**Comment by niklasmohrin** [comment]
I'll add it

**Comment by niklasmohrin** [comment]
Never found the time to conclude this, closing as outdated

**Pull request closed without merging**
