### PR TITLE
Add auto generate completions for some shells

### PR DESCRIPTION
**Pull request by SergioRibera**
This is a requested function that solves problem #268 by generating automatic autocompletions and allows updating the cache

- [x] Check format
- [x] Check clippy
- [x] test commands implementation

### Supported Shells
- Bash
- Zsh
- Fish
- Powershell
- Elvish

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! This issue (auto-generated completions) was originally tracked in https://github.com/dbrgn/tealdeer/issues/220 and a resolution attempt was started in https://github.com/dbrgn/tealdeer/pull/256 and https://github.com/dbrgn/tealdeer/pull/273. However, we noticed that the generated completions do not support dynamically generated values (i.e. completing the TLDR pages that are installed on the system). Your proposal probably doesn't have a solution for dynamic completions (#256) either, right?

**Comment by SergioRibera** [comment]
> Thanks! This issue (auto-generated completions) was originally tracked in #220 and a resolution attempt was started in #256 and #273. However, we noticed that the generated completions do not support dynamically generated values (i.e. completing the TLDR pages that are installed on the system). Your proposal probably doesn't have a solution for dynamic completions (#256) either, right?

You are right, I guess I had not seen that, but I think I can implement it with the base I have so far, I will update the PR and let you know if I get something or not to close this PR, thank you very much.

**Comment by niklasmohrin** [comment]
@SergioRibera Do you want to keep working on this, or should we close this PR for now?

**Comment by SergioRibera** [comment]
I've been busy with other things, so I think you can close the PR for now.

**Comment by niklasmohrin** [comment]
Alright, no problem :)

**Pull request closed without merging**
