### PR TITLE
Switch to maintained app_dirs

### PR DESCRIPTION
**Pull request by kornelski**

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks! References to the crate need to be updated though:

```
26 | use app_dirs::AppInfo;
   |     ^^^^^^^^ use of undeclared type or module `app_dirs`
```

**Comment by dbrgn** [comment]
The failing test is probably due to #126.

@niklasmohrin in case you'd like to cherry-pick your test fix into a separate pull request, that would be welcome!

**Comment by niklasmohrin** [comment]
Sure thing, see #128

**Comment by dbrgn** [comment]
Thanks! #128 is merged, so this branch can be rebased.

**Pull request merged**
