### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by mystal**
Continuing the work from #59.

### CODE REVIEW

**Comment by dbrgn** [comment]
@mystal thanks a lot for the PR! :rocket: 

I'm quite busy at the moment, but will try to take a look at the PR this week. Should I forget, please ping me!

**Comment by mystal** [comment]
@dbrgn Quick ping, as requested :)

**Comment by dbrgn** [comment]
Finally, looks good now! Thanks @mystal and sorry for the delay.

Last request, in #59 you wrote:

> For now I suggest we tell devs on Windows to set their git config to check out tealdeer using Unix-style line endings.

I think this could be configured with the [.gitattributes file](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings), could you verify that?

**Comment by mystal** [comment]
Oh yeah, looks like a `.gitattributes` file was already added in the original PR. Should be good to go! 👍

**Comment by dbrgn** [comment]
Great, let's merge this! :slightly_smiling_face: Thanks @mystal.

Next step would be getting #52 to run.

**Pull request merged**
